python3 starter.py -r input_data/Carro csv parquet
python3 starter.py -r input_data/Carro csv json
python3 starter.py -r input_data/Carro csv delta
python3 starter.py -r input_data/Streaming json parquet
python3 starter.py -r input_data/Streaming json csv
python3 starter.py -r input_data/Streaming json delta
python3 starter.py -r input_data/Atividades parquet csv
python3 starter.py -r input_data/Atividades parquet json
python3 starter.py -r input_data/Atividades parquet delta
python3 starter.py -r input_data/Churn csv json
python3 starter.py -r input_data/Churn csv parquet
python3 starter.py -r input_data/Churn csv delta
python3 starter.py -r input_data/Iris csv json
python3 starter.py -r input_data/Iris csv parquet
python3 starter.py -r input_data/Iris csv delta
python3 starter.py -r input_data/Mongo json csv
python3 starter.py -r input_data/Mongo json parquet
python3 starter.py -r input_data/Mongo json delta