python3 starter.py -r input_data/Carros.csv csv parquet
python3 starter.py -r input_data/Carros.csv csv json
python3 starter.py -r input_data/streaming json parquet
python3 starter.py -r input_data/streaming json csv
python3 starter.py -r input_data/Atividades parquet csv
python3 starter.py -r input_data/Atividades parquet json
python3 starter.py -r input_data/Churn csv json
python3 starter.py -r input_data/Churn csv parquet
python3 starter.py -r input_data/Iris csv json
python3 starter.py -r input_data/Iris csv parquet
python3 starter.py -r input_data/mongo json csv
python3 starter.py -r input_data/mongo json parquet
python3 starter.py -r input_data/saude_2022.csv csv json
python3 starter.py -r input_data/saude_2022.csv csv parquet